name: Update Formula

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'  # 每月的1号和15号定时更新

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Set environment variables
        run: |
          echo "VERSION=202504201540" >> $GITHUB_ENV
          echo "linux_armv7_url=https://github.com/sb-community/sing-box-premium/releases/download/202504201540/sing-box-release-linux-armv7.tar.gz" >> $GITHUB_ENV
          echo "linux_armv7_sha=0ef59d7c762af309398f7a4e99dffb2df3a7f15633466a7d5c5b9169a798eea2" >> $GITHUB_ENV
          echo "linux_armv8_url=https://github.com/sb-community/sing-box-premium/releases/download/202504201540/sing-box-release-linux-armv8.tar.gz" >> $GITHUB_ENV
          echo "linux_armv8_sha=a9194326d0f568ddd1b6471a124469910478959364695b96b7741eb058e413c4" >> $GITHUB_ENV
          echo "darwin_arm_url=https://github.com/sb-community/sing-box-premium/releases/download/202504201540/sing-box-release-darwin-arm64.tar.gz" >> $GITHUB_ENV
          echo "darwin_arm_sha=5483acf5ccfbb9bc0e86dac8a4d94efc004d77777c0f19a5341df6ebe6cfe90e" >> $GITHUB_ENV
          echo "linux_amd64_url=https://github.com/sb-community/sing-box-premium/releases/download/202504201540/sing-box-release-linux-amd64.tar.gz" >> $GITHUB_ENV
          echo "linux_amd64_sha=f1e5500d9789e2c3f9244b17b9d52acca578f9b63bca971a84f86402a83e0e83" >> $GITHUB_ENV
          echo "darwin_amd64_url=https://github.com/sb-community/sing-box-premium/releases/download/202504201540/sing-box-release-darwin-amd64.tar.gz" >> $GITHUB_ENV
          echo "darwin_amd64_sha=3572ef2a7174fdd7043f1813dac880607bea285709ecdc67487f7757fe770baf" >> $GITHUB_ENV

      - name: Generate Formula from Template
        run: |
          TEMPLATE=brew.rb
          OUTPUT=Formula/sing-box-premium.rb

          mkdir -p Formula

          # Replace placeholders in the template with actual values
          sed -e "s|{{version}}|$VERSION|g" \
              -e "s|{{darwin_arm_url}}|\"$darwin_arm_url\"|g" \
              -e "s|{{darwin_arm_sha256}}|$darwin_arm_sha|g" \
              -e "s|{{darwin_amd64_url}}|\"$darwin_amd64_url\"|g" \
              -e "s|{{darwin_amd64_sha256}}|$darwin_amd64_sha|g" \
              -e "s|{{linux_amd64_url}}|\"$linux_amd64_url\"|g" \
              -e "s|{{linux_amd64_sha256}}|$linux_amd64_sha|g" \
              -e "s|{{linux_armv8_url}}|\"$linux_armv8_url\"|g" \
              -e "s|{{linux_armv8_sha256}}|$linux_armv8_sha|g" \
              -e "s|{{linux_armv7_url}}|\"$linux_armv7_url\"|g" \
              -e "s|{{linux_armv7_sha256}}|$linux_armv7_sha|g" \
              "$TEMPLATE" > "$OUTPUT"

      - name: Commit and Push Formula
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Ensure you're pushing to the correct repository
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sb-community/homebrew-sing-box-premium.git

          git add Formula/sing-box-premium.rb
          git commit -m "Update formula to version $VERSION" || echo "No changes"
          git push origin HEAD:main
